1. Initialize an empty array with size 2X2.

In [2]:
import numpy as np

a = np.empty((2,2))
print(a)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 3.78289378e-307]]


2. Initialize an all one array with size 4X2.

In [4]:
one = np.ones((4,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [9]:
array = np.full(one.shape, 32)
print(array)

[[32 32]
 [32 32]
 [32 32]
 [32 32]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [11]:
arr2 = np.zeros_like(one.shape)
print(arr2)

[0 0]


Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [18]:
arr3 = np.ones_like([[4,2],[2,4]])
print(arr3)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [23]:
new_list = [1,2,3,4]

nparray = np.array((new_list))
print(nparray)
print(type(nparray))

[1 2 3 4]
<class 'numpy.ndarray'>


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arange()}.

In [27]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [29]:
arr = np.array([0,1,2,3,4,5,6,7,8])

mat = np.reshape(arr, (3,3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [35]:
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [45]:
rand_arry = np.random.random(30)
print(rand_arry)
mean_rand = rand_arry.mean()
print(mean_rand)

[0.51878425 0.12956832 0.72757878 0.95125022 0.40100699 0.58686788
 0.69631258 0.10848822 0.41797149 0.01570853 0.4379368  0.42915847
 0.76411855 0.44488271 0.82651345 0.92948714 0.44722159 0.71931775
 0.17653857 0.64148238 0.81570703 0.52412672 0.10914328 0.63538241
 0.20228077 0.08473527 0.23143749 0.90761823 0.26547487 0.24055078]
0.47955505075290566


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [50]:
arr = np.random.randint(100,size=(10,10))
print(arr)

min_arr = arr.min()
max_arr = arr.max()

print(min_arr)
print(max_arr)

[[17 97 42  3  2 25 68 12 13  8]
 [59  0 73 90 90 27  2 76 11 42]
 [19 25 12 58 73 81 30 71 45 74]
 [10 95 54 23  8 97 55 95 16 70]
 [97 91 80 67 28 49 92 96 56 38]
 [50 38 40 42 60 90 31 69 85  0]
 [27 98 46 48 91 70 77 28 56 25]
 [99 28 31 19 29 46 44 46 75 50]
 [54 82 86  2 73 43 99  4 19 73]
 [57 20 89 71 20 67 36  7  9  9]]
0
99


6. Create a zero array of size 10 and replace 5th element with 1.

In [55]:
arr = np.arange(0,10)
print(arr)
arr[4] = 1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 1 5 6 7 8 9]


7. Reverse an array arr = [1,2,0,0,4,0].

In [60]:
arr = [1,2,0,0,4,0]
print(arr[::-1])

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [68]:
arr = np.ones((4,5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [73]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set 1s at odd rows, even columns
checkerboard[::2, 1::2] = 1  # Set 1s at even rows, odd columns

print(checkerboard)
    

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [91]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.

In [77]:
add_mat = x + y
print(add_mat)

add_mat2 = v + w
print(add_mat2)

[[ 6  8]
 [10 13]]
[20 22]


2. Subtract the two array.

In [78]:
sub_mat = x - y
print(sub_mat)

[[-4 -4]
 [-4 -3]]


In [82]:
mul = x*3
print(mul)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [84]:
sq = x*x
print(sq)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [87]:
xdoty = np.dot(x,y)
print(xdoty)

xdotv = np.dot(x,v)
print(xdotv)

[[19 22]
 [50 58]]
[29 77]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [95]:
cat = np.concatenate((v,w))
print(cat)

cat2 = np.vstack((x,y))
print(cat2)

[ 9 10 11 12]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [96]:
cat3 = np.hstack((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

In [98]:
A = np.array([[3,4],[7,8]]) 
B = np.array([[5,3],[2,1]])

In [103]:
Ainv = np.linalg.inv(A)
print(Ainv)

axAinv = np.dot(A, Ainv)
print(axAinv)

[[-2.    1.  ]
 [ 1.75 -0.75]]
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [105]:
AB = np.dot(A,B)
print(AB)

BA = np.dot(B,A)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [106]:
AB_T = (A @ B).T
BTAT = B.T @ A.T
print("3. (AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_T, BTAT))

3. (AB)ᵀ = BᵀAᵀ: True
